gui:
  showRandomTip: false
  nerdFontsVersion: '3'
  sidePanelWidth: 0.2
  border: 'single'
  mainPanelSplitMode: 'vertical'
  useHunkModeInStagingView: false

git:
  pagers:
    - pager: 'delta --dark --paging=never'

notARepository: 'skip'
