k9s:
  # use `k9s --write` to manually override this and make destructive changes
  readOnly: true
  ui:
    logoless: true
    enableMouse: true
    reactive: true
  logger:
    showTime: true
    textWrap: true
